services:
  caddy:
    image: caddy:2-alpine
    container_name: radio_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - radio_network
    depends_on:
      - api

  api:
    image: ghcr.io/casa-13-radio/radio-api:latest
    container_name: radio_api
    restart: unless-stopped
    expose:
      - "3000" # Só acessível dentro da rede Docker
    environment:
      - ENVIRONMENT=production
    networks:
      - radio_network

networks:
  radio_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: